steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "eu.gcr.io/trade-and-play/trade-and-play-api-production:$COMMIT_SHA",
        ".",
      ]
  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "eu.gcr.io/trade-and-play/trade-and-play-api-production:$COMMIT_SHA",
      ]
  # Deploy container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "trade-and-play-api-production:${_ENV}",
        "--image",
        "eu.gcr.io/trade-and-play/trade-and-play-api-production:$COMMIT_SHA",
        "--region",
        "europe-west4",
        "--platform",
        "managed",
      ]
images:
  - eu.gcr.io/trade-and-play/trade-and-play-api-production:$COMMIT_SHA
